# .goreleaser.yml
version: 2

project_name: cloud-policy-serializer

builds:
- id: cloud-easy-connector
  main: ./cmd
  binary: cloud-policy-serializer
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm64
  - arm

release:
  name_template: "Release {{ .Tag }}"
  disable: true
  github:
    owner: raywall
    name: cloud-policy-serializer

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - 'Merge pull request'
    - 'Merge branch'
